version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  shared:
    build:
      context: .
      dockerfile: shared/Dockerfile
    volumes:
      - shared_node_modules:/app/node_modules

  movie-service:
    build:
      context: .
      dockerfile: services/movie-service/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://movie-service-user:password123@mongodb:27017/movie-service?authSource=admin
      - REDIS_URI=redis://redis:6379
      - DIRECTOR_SERVICE_URL=http://director-service:3001
    volumes:
      - ./services/movie-service:/app/movie-service
      - movie_service_node_modules:/app/node_modules
    depends_on:
      - mongodb
      - redis
      - shared

  director-service:
    build:
      context: .
      dockerfile: services/director-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://director-service-user:password123@mongodb:27017/director-service?authSource=admin
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./services/director-service:/app/director-service
      - director_service_node_modules:/app/node_modules
    depends_on:
      - mongodb
      - redis
      - shared

volumes:
  mongodb_data:
  redis_data:
  shared_node_modules:
  movie_service_node_modules:
  director_service_node_modules: 